### PR TITLE
add layout twig file and empty css file based on silex skeleton files

### PR DESCRIPTION
**Pull request by anacona16**

### CODE REVIEW

**Comment by cawa87** [comment]
I think because of micro-framework, maybe it would be a nice idea to [deal with twig directly].(http://symfony.com/blog/new-in-symfony-2-7-twig-as-a-first-class-citizen)

**Comment by anacona16** [comment]
Ok, but anyway need some templates, right?

**Comment by cawa87** [comment]
yes, but better not to use template inheritance

**Comment by anacona16** [comment]
I think that the use of two different templates with some equal code need template inheritance, this is one of the most useful twig features.

**Pull request merged**
